name: Clair Push

on:
  workflow_dispatch:

jobs:
  update-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Clair Push Script
        run: |
          python clair_scripts/clair_push.py
